wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 128
hidden_size:
  desc: null
  value: 128
